### ISSUE TITLE
[Bug]: Tags with names starting with '!' cause xml parse errors

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/Hermes#22]
### Bug Description

Tags with names starting with '!' cause xml parse errors (at least on macOS).

I'll test on my pc later, time permitting.

### How to Reproduce?

Enter a tag like `<!italic>`, `<!b>`, inside an enclosing `<text>` element as intended, in a quest description. Close editor.

### Expected Behavior

Amazing style cancellation action! (Seriously though, these '!' tags are a neat idea).

### Version

current

### Mod Loader Version

current

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by SubordinalBlue** [comment]
Also errors on my Win10 and Linux machines.

To be clear: I'm referring to the tags names that begin with a '!' that are added to the `serializers` HashMap in `TextTagProvider.java`

**Comment by ThatGravyBoat** [comment]
Removed in 1.21 with better alternatives
